version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
  app:
    build: .
    environment:
      MIX_ENV: dev
    ports:
      - "4000:4000"
    depends_on:
      - db
